### PR TITLE
[WIP] add imgui controls for define macros

### PR DESCRIPTION
**Pull request by Vipitis**
Very WIP, so the branch is messy. Mentioned in #8

I threw this together at the airport just now after thinking about it for the past week. 

Currently works with the example provided but theoretically should work with all single pass shaders. 
Only float and int dtypes and only glsl just now. Also missing common code. 

Based on the imgui example in wgpu, but I can already think of a bunch of ways to make it fit better with the existing structures. 

most likely todos:
* [x] better example, perhaps this: https://www.shadertoy.com/view/Wf3SWn (needs to loop in L73)
* [ ] can we somehow access the preprocessor from naga (or via tree-sitter?)
* [x] add a dataclass to hold all the information
* [x] support common and buffer passes like `buffer_a.value`
* [ ] can imgui be it's own renderpass (instead of attaching to the image?)
* [x] Sliders should have an option to reset to default
* [x] Print the value off all constants upon exit (`on_close` event?)
* [ ] skip common constants (pi, tau, eps?, ...)
* [ ] vec3 dtype for color picker and directions!?
* [ ] can we get `const float name 1.23` too?
* [ ] a bunch of tests
* [ ] should this be an optional dependency
* [ ] does imgui-bundle work with python3.9 or do we need to drop it?
* [ ] WGSL has no `#define` - do we support any patterns there?
* [ ] cleanup

### CODE REVIEW

**Comment by Vipitis** [comment]
little demo video to show the poc working from cli:

https://github.com/user-attachments/assets/1cc066a5-826a-431a-b10a-c1f6ac096d4d

**Comment by Korijn** [comment]
This is super cool!

**Comment by ShnitzelKiller** [comment]
I get the error `AttributeError: 'imgui_bundle._imgui_bundle.imgui.ImFontAtlas' object has no attribute 'get_tex_data_as_rgba32'` when I try to launch a shader with the --imgui argument. On macOSX.

**Comment by Vipitis** [comment]
Hey @ShnitzelKiller can you try out the `wgpu` main brach? The latest release is missing some fixes for the most recent imgui-bundle release see https://github.com/pygfx/wgpu-py/pull/725

Otherwise downgrading imgui-bundle might do it.

**Comment by ShnitzelKiller** [comment]
Installing `main` branch of `wgpu` fixed it.

File: wgpu_shadertoy/imgui.py [hunk 1]
```diff
@@ -0,0 +1,227 @@
...
+                    main._common_constants_data[const.name] = const.value
+
+    for rp in renderpasses: # TODO: most likely add common here?
+        constants = rp._constants
+        constants_data = rp._constants_data
+        if ig.collapsing_header(f"{rp} Constants", flags=ig.TreeNodeFlags_.default_open):
+            if hasattr(rp, "texture_front"): # isinstance(rp, BufferRenderPass)
+                # make this another toggle? or a whole 2nd UI?
+                front_view = rp.texture_front.create_view()
+                front_ref = rp.main._imgui_backend.register_texture(front_view)
```
Comment (panxinmiao) [inline wgpu_shadertoy/imgui.py:192]: Hi, came cross here from https://github.com/pygfx/wgpu-py/issues/729#issuecomment-3172852887.
It’s generally better not to create and register new texture views every frame in the render loop. Instead, a global texture view should be registered and used during initialization, or a imgui.TextureRef can be registered and created only at the first time the GUI is rendered.
If it’s absolutely necessary to create and register new texture views each frame in the render loop, you must manually call the newly added `unregister` method in https://github.com/pygfx/wgpu-py/pull/749 to release the old texture view resources.

Comment (Vipitis) [reply wgpu_shadertoy/imgui.py:192]: cheers for the heads up,
the render target for the buffer passes is switching back and forth between two textures(maybe I should also keep both views...) so I will likely have to register both of them during initialization and figure out a way to select the correct one in the gui function or swap them around after the draw function too. Sorta is a little against the "intermediate mode" concept.

I will have a think since this whole branch needs a better pattern anyway, why too many `if self._imgui`
